jQuery(document).ready(function(){if(document.getElementById('elections-countdown')){updateClock();}});function updateClock(){var currenttime=(new Date()).getTime();var timeleft=Math.floor((elections_targettime- currenttime)/1000);if(timeleft>0){var daysleft=Math.floor(timeleft/(60*60*24));timeleft%=(60*60*24);var hoursleft=Math.floor(timeleft/(60*60));timeleft%=(60*60);var minutesleft=Math.floor(timeleft/60);timeleft%=(60);var secondsleft=Math.floor(timeleft);var daystext='';var hourstext='';var minutestext='';var secondstext='';if(daysleft>0){daystext='<span class="elections-countdown-number">'+ daysleft+'</span> day'+((daysleft==1)?'':'s')+', ';}
if(!((daysleft=='')&&(hoursleft==0))){hourstext='<span class="elections-countdown-number">'+ hoursleft+'</span> hour'+((hoursleft==1)?'':'s')+', ';}
if(!((hoursleft=='')&&(minutesleft==0))){minutestext='<span class="elections-countdown-number">'+ minutesleft+'</span> minute'+((minutesleft==1)?'':'s')+' and ';}
if(!((minutesleft=='')&&(secondsleft==0))){secondstext='<span class="elections-countdown-number">'+((secondsleft<10)?'0':'')+ secondsleft+'</span> seconds';}
document.getElementById('elections-countdown').innerHTML=daystext+ hourstext+ minutestext+ secondstext+' until '+ elections_countdown['message'];setTimeout('updateClock()',1000);}else{document.getElementById('elections-countdown').style.display='none';document.getElementById('elections-countdown').innerHTML='';}}
function changeTab()
{if(jQuery(this).hasClass('active')){return false;}
var cat=jQuery(this).attr('id').split('_')[0];var id=jQuery(this).attr('id').split('_')[2];jQuery('#cat1_tab_'+ id).removeClass("active");jQuery('#cat2_tab_'+ id).removeClass("active");jQuery('#cat3_tab_'+ id).removeClass("active");jQuery('#cat4_tab_'+ id).removeClass("active");jQuery('#'+ cat+'_tab_'+ id).addClass('active');jQuery('#cat1_box_'+ id).hide();jQuery('#cat2_box_'+ id).hide();jQuery('#cat3_box_'+ id).hide();jQuery('#cat4_box_'+ id).hide();jQuery('#'+ cat+'_box_'+ id).fadeIn('fast');return false;}
jQuery(document).ready(function(){jQuery('.cat1_tab').click(changeTab);jQuery('.cat2_tab').click(changeTab);jQuery('.cat3_tab').click(changeTab);jQuery('.cat4_tab').click(changeTab);jQuery('.cat1_tab').click();});var candidate_box_height=530;var candidate_box_width=730;var candidate_box;var grey_shade;function page_height(){return(document.height!==undefined)?document.height:document.body.offsetHeight;}
function viewable_height(){var myHeight=0;if(typeof(window.innerWidth)=='number'){myHeight=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){myHeight=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){myHeight=document.body.clientHeight;}
return myHeight;}
function viewable_width(){var myWidth=0;if(typeof(window.innerWidth)=='number'){myWidth=window.innerWidth;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){myWidth=document.documentElement.clientWidth;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){myWidth=document.body.clientWidth;}
return myWidth;}
function getScrollXY(){var scrOfX=0,scrOfY=0;if(typeof(window.pageYOffset)=='number'){scrOfY=window.pageYOffset;scrOfX=window.pageXOffset;}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){scrOfY=document.body.scrollTop;scrOfX=document.body.scrollLeft;}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){scrOfY=document.documentElement.scrollTop;scrOfX=document.documentElement.scrollLeft;}
return[scrOfX,scrOfY];}
function candidate_box_show(id){var off_top_sum=Math.floor((viewable_height()- candidate_box_height)/2);var off_left_sum=Math.floor((viewable_width()- candidate_box_width)/2);var off_top=(off_top_sum<0)?0:off_top_sum;var off_left=(off_left_sum<0)?0:off_left_sum;var scrolls=getScrollXY();if(candidate_box){candidate_box.hide();}
candidate_box=jQuery('#candidate-'+ id);if(candidate_box.size()===0){candidate_box=null;return;}
candidate_box.find('a.close').click(candidate_box_close);candidate_box.css('top',(scrolls[1]+ off_top)+'px');candidate_box.css('left',(scrolls[0]+ off_left)+'px');if(parseInt(id)>52222){grey_shade.css('width','100%');grey_shade.css('height','100%');grey_shade.css('position','fixed');}else{grey_shade.css('width',viewable_width()+'px');grey_shade.css('height',page_height()+'px');}
if(!jQuery.browser.msie){grey_shade.fadeIn();}
candidate_box.show();return false;}
function candidate_box_close(){candidate_box.hide();if(!jQuery.browser.msie){grey_shade.fadeOut('fast');}
candidate_box=null;return false;}
function candidates_click(){var link=jQuery(this);var id=link.attr('id').substr(5);return candidate_box_show(id);}
function candidates_init(){jQuery(document).keyup(function(e){if(e.keyCode==27){candidate_box_close();}});grey_shade=jQuery('#grey-shade');if(grey_shade.size()===0){return;}
jQuery('.candidate a').click(candidates_click);jQuery('.list-divs a').click(candidates_click);grey_shade.click(candidate_box_close);}
jQuery(candidates_init);function candidates_hash(){var id=jQuery(this).attr('id').substr(5);window.location.replace('#!/'+id);return false;}
jQuery(document).ready(function(){var loadedhash=window.location.hash.split('/');if(loadedhash[1]){candidate_box_show(loadedhash[1]);}
jQuery('.elections2011 .candidate a').click(candidates_hash);jQuery('.elections2011 ul a').click(candidates_hash);jQuery('.candidate-box-close').click(function(){window.location.replace('#!/');candidate_box_close();return false;});jQuery('#grey-shade').click(function(){window.location.replace('#!/');});jQuery(document).keyup(function(e){if(e.keyCode==27){window.location.replace('#!/');}});});jQuery(document).ready(function(){jQuery('.fbshare a').click(function(){window.open(jQuery(this).attr('href'),'sharer','toolbar=0,status=0,width=626,height=436');return false;});});function elections_timeline(){jQuery('#elections-timeline a').click(function(){jQuery('#elections-timeline-content').toggle('fast');return false;});}
jQuery(elections_timeline);function new_elections_timeline(){jQuery('#elections-timeline-box').click(function(){var the_link=jQuery('a',this);if(jQuery(the_link).text()=='+'){the_link.data('topmargin',jQuery('div',this).css('marginTop'));jQuery('div',this).stop(true,true).animate({marginTop:'0'},'medium');jQuery(this).stop(true,true).animate({height:'+=163'},'medium',function(){jQuery(the_link).text('-');});}else{jQuery('div',this).stop(true,true).animate({marginTop:the_link.data('topmargin')},'medium');jQuery(this).stop(true,true).animate({height:'-=163'},'medium',function(){jQuery(the_link).text('+');});}
return false;});}
jQuery(new_elections_timeline);var video_active_link=0;var video_first_shown=1;var video_last_loaded=0;var video_page_display=3;var video_array_length;var video_item_width=0;var player;jQuery(document).ready(function(){if(document.getElementById('vid-holder')){video_array_length=elections_videos.length;if(video_array_length==0){document.getElementById('vid-object').innerHTML='';document.getElementById('vid-list-holder').innerHTML='<h3 style="text-align: center; line-height: 35px;">No videos available yet</h3>';}else{video_initialise();}}
jQuery('#vid-list li a').live('click',function(){if(video_active_link!=jQuery(this).attr('id')){jQuery('#vid-list li a').removeClass('vid-active');jQuery(this).addClass('vid-active');video_update_object(jQuery(this).attr('id'),true);video_active_link=jQuery(this).attr('id');}
return false;});jQuery('#vid-left').click(function(){if(video_array_length>video_page_display&&video_first_shown>1){jQuery('#vid-list').animate({'left':'+='+video_item_width+'px'},400,function(){video_first_shown--;});}
return false;});jQuery('#vid-right').click(function(){if(video_array_length>video_page_display){if(video_first_shown<(video_array_length- 1)){if((video_first_shown+ video_page_display- 1)==video_last_loaded){video_add_next();}
jQuery('#vid-list').animate({'left':'-='+video_item_width+'px'},400,function(){video_first_shown++;});}else{jQuery('#vid-list').animate({'left':'0px'},400,function(){video_first_shown=1;});}}
return false;});});function video_initialise(){document.getElementById('vid-list').innerHTML='';for(i=0;i<video_array_length&&i<video_page_display;i++){video_add_next();}
jQuery('#vid-list li:first a').addClass('vid-active');video_update_object(elections_videos[0]['id'],false);video_active_link=jQuery('#vid-list li:first a').attr('id');}
function video_add_next(){if(video_last_loaded<video_array_length){document.getElementById('vid-list').innerHTML+=video_item_construct(elections_videos[video_last_loaded]);if(video_last_loaded==0){video_item_width=jQuery('#vid-list li:first a').outerWidth();}
video_last_loaded++;jQuery('#vid-list').width((jQuery('#vid-list').width()+ video_item_width)+'px');}}
function video_item_construct(item_array){return'\n<li><a href="#video'+ item_array['id']+'" id="'+ item_array['id']+'">'+ item_array['title']+'</a></li>';}
function video_update_object(id,autostart){player=new SWFObject('/wp-content/plugins/nouse-ystv/mediaplayer.swf','ystvplayer','386','310','7');player.addParam('allowfullscreen','true');player.addParam('width','386');player.addParam('height','310');player.addVariable('width','386');player.addVariable('height','310');if(autostart){player.addVariable('autostart','true');}
player.addVariable('file','http://ystv.york.ac.uk/static/videos.php?file='+ id);player.addVariable('logo','/wp-content/plugins/nouse-ystv/ystv_logo.png');player.addVariable('type','video');player.addVariable('plugins','googlytics-1');player.write('vid-object');}
var marquee_array_length;var marquee_width;var marquee_duration_default=70000;var marquee_duration_fast=(marquee_duration_default/4);var marquee_direction='left';var marquee_duration=marquee_duration_default;var marquee_is_fast=false;jQuery(document).ready(function(){if(document.getElementById('marquee-holder')){marquee_array_length=candidate_data.length;if(marquee_array_length==0){jQuery('#marquee-holder').hide();}else{marquee_initialise();}}
jQuery('#marquee-list-holder').hover(function(){marquee_stop();},function(){marquee_move();});jQuery('.marquee-arrow').click(function(){return false;});jQuery('.marquee-arrow').hover(function(){if(jQuery(this).attr('id')=='marquee-left'){marquee_direction='left';}else{marquee_direction='right';}
marquee_is_fast=true;marquee_move();},function(){marquee_is_fast=false;marquee_move();});});function marquee_initialise(){document.getElementById('marquee-list').innerHTML='';for(var i=0;i<marquee_array_length;i++){document.getElementById('marquee-list').innerHTML+=marquee_item_construct(candidate_data[i]);}
marquee_width=marquee_array_length*jQuery('#marquee-list a:first').outerWidth(true);jQuery('#marquee-list').width((marquee_width*2)+'px');for(var j=0;j<marquee_array_length;j++){document.getElementById('marquee-list').innerHTML+=marquee_item_construct(candidate_data[j]);}
marquee_move();}
function marquee_calc(){if(marquee_direction=='left'){marquee_duration=(1-(Math.abs(parseInt(jQuery('#marquee-list').css('marginLeft'),10))/marquee_width));}else{marquee_duration=(Math.abs(parseInt(jQuery('#marquee-list').css('marginLeft'),10))/marquee_width);}
if(marquee_is_fast){marquee_duration=marquee_duration_fast*marquee_duration;}else{marquee_duration=marquee_duration_default*marquee_duration;}}
function marquee_move(){marquee_stop();marquee_calc();if(marquee_direction=='left'){jQuery('#marquee-list').animate({marginLeft:'-'+marquee_width+'px'},marquee_duration,'linear',function(){jQuery(this).css('marginLeft',0);var again=setTimeout('marquee_move()',10);});}else{jQuery('#marquee-list').animate({marginLeft:'0px'},marquee_duration,'linear',function(){jQuery(this).css('marginLeft','-'+marquee_width+'px');var again=setTimeout('marquee_move()',10);});}}
function marquee_stop(){jQuery('#marquee-list').stop(true);}
function marquee_item_construct(item){return'\n<a href="/elections/candidates/#!/'+ item['id']+'"><img src="'+ item['img']+'" /><br />'+ item['name']+'<br /><em>'+ item['position']+'</em></a>';}